import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://surveyenginerc.taxcreditco.com/survey.aspx?enc=5a209mATlQcKyXM3xRqb6z9qoFI14Q1%2beuSy4Mvyz4F8b8A4fB6L2uEXfKik6kiCktvzGeqTOq0UG67Ti7QMMKDdhjh3KJTZme0Ugry8N7PenULbtCq%2bCn54k%2fpHP2%2boOewCjvCII3inlEc52rpRut6QWAMxj10M3%2b%2fzgTJ%2f7i%2fRi07j8G0bZzUvqoT1aDy52A4B%2bhXUBBqRwavZS%2fD35bkQajqLUMu30ey7OJgIjQ3RfAPrjC%2fl0z6ZBz8WiBkjGpQyGr69qYNdVNETBH8pAjA4yOl1zhPSIxjp8dxJcFw%3d');
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('Tony');
  await page.getByLabel('First Name').press('Tab');
  await page.getByLabel('Last Name').fill('Start');
  await page.getByLabel('Last Name').press('Tab');
  await page.getByLabel('Email Address').fill('tonystart001@gmail.com');
  await page.getByLabel('Email Address').press('Tab');
  await page.getByLabel('Street Address').fill('Kingston Street');
  await page.getByLabel('Street Address').press('Tab');
  await page.getByLabel('City').fill('Chennai');
  await page.getByLabel('City').press('Tab');
  await page.getByLabel('Zip Code').fill('603003');
  await page.getByLabel('First Name').click();
  await page.getByLabel('Last Name').click();
  await page.getByLabel('Email Address').click();
  await page.getByLabel('Street Address').click();
  await page.getByLabel('City').click();
  await page.getByLabel('Zip Code').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Zip Code').click();
  await page.getByLabel('Zip Code').fill('603103');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Zip Code').click();
  await page.getByLabel('Zip Code').press('ArrowLeft');
  await page.getByLabel('Zip Code').press('ArrowLeft');
  await page.getByLabel('Zip Code').press('ArrowLeft');
  await page.getByLabel('Zip Code').fill('603-103');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('City').click();
  await page.getByLabel('City').press('ControlOrMeta+a');
  await page.getByLabel('City').fill('Indianapolis');
  await page.getByLabel('Zip Code').click();
  await page.getByLabel('Zip Code').press('ControlOrMeta+a');
  await page.getByLabel('Zip Code').fill('46204');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('In the last year, have you or').click();
  await page.locator('#SurveyControl_Question11396').getByText('No').click();
  await page.getByText('In the last two years, have').click();
  await page.locator('#SurveyControl_Question11397').getByText('No').click();
  await page.getByText('Are you a veteran of the U.S').click();
  await page.locator('#SurveyControl_Question914').getByText('No').click();
  await page.getByText('Are you a person who has a').click();
  await page.locator('#SurveyControl_Question11361').getByText('No').click();
  await page.getByText('Have you ever been convicted').click();
  await page.locator('#SurveyControl_Question915').getByText('No').click();
  await page.getByText('Are you unemployed?AndHave').click();
  await page.locator('#SurveyControl_Question1244').getByText('No').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Additional Information Thank').click();
  await page.getByRole('button', { name: 'Submit form' }).click();
});